
exports.productionField = {

    "PROD_1"    : { "key" : "Cumulative Hanks", "values" :"4" },
    "PROD_2"    : { "key" : "run time", "values" :"2" },
    "PROD_3"    : { "key" : "idle time", "values" : "2" },
    "PROD_4"    : { "key" : "doff time", "values" : "2" },
    "PROD_5"    : { "key" : "power fail time", "values" : "2" },
    "PROD_6"    : { "key" : "length1", "values" : "2" },
    "PROD_7"    : { "key" : "speed", "values" : "2" },
    "PROD_8"    : { "key" : "meter per minute", "values" : "2" },
    "PROD_9"    : { "key" : "shift hanks", "values" : "2" },
    "PROD_10"   : { "key" : "shift kwh", "values" : "4" },
    "PROD_11"   : { "key" : "shift KW", "values" : "4" },
    "PROD_12"   : { "key" : "M/C status", "values" : "1" },
    "PROD_13"   : { "key" : "No of doff", "values" : "2" },
    "PROD_14"   : { "key" : "production", "values" : "2" },
    "PROD_15"   : { "key" : "count", "values" : "2" },
    "PROD_16"   : { "key" : "TPI", "values" : "2" },
    "PROD_17"   : { "key" : "Efficiency", "values" : "2" },
    "PROD_18"   : { "key" : "UNITS(KWH Cumulative)", "values" : "2" },
    "PROD_19"   : { "key" : "UKG", "values" : "2" },
    "PROD_20"   : { "key" : "Delivery Speed", "values" : "2" },
    "PROD_21"   : { "key" : "Average Speed", "values" : "2" },
    "PROD_22"   : { "key" : "Step", "values" : "2" },
    "PROD_23"   : { "key" : "Cumulative Runtime", "values" : "2" },
    "PROD_24"   : { "key" : "total downtime", "values" : "2" },
    "PROD_25"   : { "key" : "Last Doff Avg Speed", "values" : "2" },
    "PROD_26"   : { "key" : "Doff Count", "values" : "2" },
    "PROD_27"   : { "key" : "TPM", "values" : "2" },
    "PROD_28"   : { "key" : "Stop Motion1", "values" : "2" },
    "PROD_29"   : { "key" : "stop Motion2", "values" : "2" },
    "PROD_30"   : { "key" : "stop Motion3", "values" : "2" },
    "PROD_31"   : { "key" : "stop Motion4", "values" : "2" },
    "PROD_32"   : { "key" : "stop Motion count1", "values" : "2" },
    "PROD_33"   : { "key" : "stop Motion count 2", "values" : "2" },
    "PROD_34"   : { "key" : "stop Motion count 3", "values" : "2" },
    "PROD_35"   : { "key" : "stop Motion count4", "values" : "2" },
    "PROD_36"   : { "key" : "COP content", "values" : "2" },
    "PROD_37"   : { "key" : "Doff length", "values" : "2" },
    "PROD_38"   : { "key" : "Remaining Doff Time", "values" : "2" },
    "PROD_39"   : { "key" : "Shift Production", "values" : "2" },
    "SENS_1"    : { "key" : "sensor1 pulse/min", "values" : "4" },
    "SENS_2"    : { "key" : "sensor2 pulse/min", "values" : "4" },
    "SENS_3"    : { "key" : "sensor3 pulse/min", "values" : "4" },
    "SENS_4"    : { "key" : "sensor4 pulse/min", "values" : "4" },
    "SENS_5"    : { "key" : "Digital input 1 status", "values" : "1" },
    "SENS_6"    : { "key" : "Digital input 2 status", "values" : "1" },
    "SENS_7"    : { "key" : "Digital input 3 status", "values" : "1" },
    "SENS_8"    : { "key" : "Digital input 4 status", "values" : "1" },
    "SENS_9"    : { "key" : "Digital input 1 counter", "values" : "2" },
    "SENS_10"   : { "key" : "Digital input 2 counter", "values" : "2" },
    "SENS_11"   : { "key" : "Digital input 3 counter", "values" : "2" },
    "SENS_12"   : { "key" : "Digital input 4 counter", "values" : "4" },
    "SENS_13"   : { "key" : "sensor3 pulse/min",       "values" : "4" },
    "SENS_14"   : { "key" : "sensor4 pulse/min",       "values" : "4" },
    "SENS_15"   : { "key" : "Digital input 1 status",  "values"  : "1" },
    "SENS_16"   : { "key" : "Digital input 2 status",  "values"  : "1" },
    "SENS_17"   : { "key" : "Digital input 3 status",  "values"  : "1" },
    "SENS_18"   : { "key" : "Digital input 4 status",  "values"  : "1" },
    "SENS_19"   : { "key" : "Digital input 1 counter", "values"  : "2" },
    "SENS_20"   : { "key" : "Digital input 2 counter", "values"  : "2" },
    "SENS_21"   : { "key" : "Analog input 1 (voltage)", "values" : "2" },
    "SENS_22"   : { "key" : "Analog input 2 (voltage)", "values" : "2" },
    "SENS_23"   : { "key" : "Analog input 1 (current)", "values" : "2" },
    "SENS_24"   : { "key" : "Analog input 2 (current)", "values" : "2" },
    "SENS_25"   : { "key" : "Analog output (voltage)", "values"  : "2" },
    "SENS_26"   : { "key" : "Analog output (current)", "values"  : "2" }

};

exports.electricalField = {

    "ELEC_1"    : { "key" : "Watts Total", "values" :"0" },
    "ELEC_2"    : { "key" : "Watts R phase", "values" :"3" },
    "ELEC_3"    : { "key" : "Watts Y phase", "values" :"3" },
    "ELEC_4"    : { "key" : "Watts B phase", "values" :"3" },
    "ELEC_5"    : { "key" : "VAR Total", "values" :"3" },
    "ELEC_6"    : { "key" : "VAR R phase", "values" :"3" },
    "ELEC_7"    : { "key" : "VAR Y phase", "values" :"3" },
    "ELEC_8"    : { "key" : "VAR B phase", "values" :"3" },
    "ELEC_9"    : { "key" : "PF Ave.(Instantaneous)", "values" :"3" },
    "ELEC_10"   : { "key" : "PF R phase", "values" :"2" },
    "ELEC_11"   : { "key" : "PF Y phase", "values" :"2" },
    "ELEC_12"   : { "key" : "PF B phase", "values" :"2" },
    "ELEC_13"   : { "key" : "VA total", "values" :"2" },
    "ELEC_14"   : { "key" :"VA R phase", "values" :"3"},   
    "ELEC_15"   : { "key" :"VA Y phase", "values" :"3"},
    "ELEC_16"   : { "key" :"VA B phase", "values" :"3"},   
    "ELEC_17"   : { "key" :"VLL average", "values" :"3"},  
    "ELEC_18"   : { "key" :"Vry phase", "values" :"1"},    
    "ELEC_19"   : { "key" :"Vyb phase", "values" :"1"},    
    "ELEC_20"   : { "key" :"Vbr phase", "values" :"1"},
    "ELEC_21"   : { "key" :"VLN average", "values" :"1"},  
    "ELEC_22"   : { "key" :"V R phase", "values" :"1"},    
    "ELEC_23"   : { "key" :"V Y phase", "values" :"1"},    
    "ELEC_24"   : { "key" :"V B phase", "values" :"1"},    
    "ELEC_25"   : { "key" :"Current Total", "values" :"1"}, 
    "ELEC_26"   : { "key" :"Current R phase", "values" :"2"},  
    "ELEC_27"   : { "key" :"Current Y phase", "values" :"2"},  
    "ELEC_28"   : { "key" :"Current B phase", "values" :"2"},  
    "ELEC_29"   : { "key" :"Frequency", "values" :"2"},    
    "ELEC_30"   : { "key" :"Wh Received (EB)", "values" :"2"}, 
    "ELEC_31"   : { "key" :"VAh Received (EB)", "values" :"4"},    
    "ELEC_32"   : { "key" :"VARh Ind. Received (EB)", "values" :"4"},  
    "ELEC_33"   : { "key" :"VARh Cap. Received (EB)", "values" :"4"},  
    "ELEC_34"   : { "key" :"Reserved", "values" :"4"}, 
    "ELEC_35"   : { "key" :"Reserved", "values" :"4"}, 
    "ELEC_36"   : { "key" :"Reserved", "values" :"4"}, 
    "ELEC_37"   : { "key" :"Reserved", "values" :"4"}, 
    "ELEC_38"   : { "key" :"PF average Received (EB)", "values" :"4"}, 
    "ELEC_39"   : { "key" :"Amps average Received (EB)", "values" :"2"},   
    "ELEC_40"   : { "key" :"Reserved", "values" :"4"}, 
    "ELEC_41"   : { "key" :"Reserved", "values" :"2"}, 
    "ELEC_42"   : { "key" :"Neutral Current", "values" :"4"},  
    "ELEC_43"   : { "key" :"Voltage R Harmonics", "values" :"2"},  
    "ELEC_44"   : { "key" :"Voltage Y Harmonics", "values" :"1"},  
    "ELEC_45"   : { "key" :"Voltage B Harmonics", "values" :"1"},  
    "ELEC_46"   : { "key" :"Current R Harmonics", "values" :"1"},  
    "ELEC_47"   : { "key" :"Current Y Harmonics", "values" :"2"},  
    "ELEC_48"   : { "key" :"Current B Harmonics", "values" :"2"},  
    "ELEC_49"   : { "key" :"Rising Demand (optional)", "values" :"2"}, 
    "ELEC_50"   : { "key" :"Forecast Demand (optional)", "values" :"3"}, 
    "ELEC_51"   : { "key" :"Maximum Demand (optional)", "values" :"3"},    
    "ELEC_52"   : { "key" :"Reserved", "values" :"3"}, 
    "ELEC_53"   : { "key" :"Reserved", "values" :"3"}, 
    "ELEC_54"   : { "key" :"Reserved", "values" :"3"}, 
    "ELEC_55"   : { "key" :"Reserved", "values" :"1"}, 
    "ELEC_56"   : { "key" :"Reserved", "values" :"1"}, 
    "ELEC_57"   : { "key" :"Reserved", "values" :"2"}, 
    "ELEC_58"   : { "key" :"RPM", "values" :"3"},  
    "ELEC_59"   : { "key" :"Load Hours Received (EB)", "values" :"4"}, 
    "ELEC_60"   : { "key" :"Reserved", "values" :"4"},   
    "ELEC_61"   : { "key" :"No of interruptions", "values" :"2"},  
    "ELEC_62"   : { "key" :"Reserved", "values" :"3"}, 
    "ELEC_63"   : { "key" :"Reserved", "values" :"4"}, 
    "ELEC_64"   : { "key" :"Reserved", "values" :"2"}, 
    "ELEC_65"   : { "key" :"Reserved", "values" :"4"}, 
    "ELEC_66"   : { "key" :"Reserved", "values" :"2"}, 
    "ELEC_67"   : { "key" :"Voltage R phase angle", "values" :"3"},    
    "ELEC_68"   : { "key" :"Voltage Y phase angle", "values" :"4"},    
    "ELEC_69"   : { "key" :"Voltage B phase angle", "values" :"2"},    
    "ELEC_70"   : { "key" :"Current R phase angle", "values" :"4"},   
    "ELEC_71"   : { "key" :"Current Y phase angle", "values" :"1"},   
    "ELEC_72"   : { "key" :"Current B phase angle", "values" :"1"},   
    "ELEC_73"   : { "key" :"TOD Slot-1  (optional)", "values" :"1"},  
    "ELEC_74"   : { "key" :"TOD Slot-2  (optional)", "values" :"2"},   
    "ELEC_75"   : { "key" :"TOD Slot-3  (optional)", "values" :"2"},  
    "ELEC_76"   : { "key" :"TOD Slot-4  (optional)", "values" :"2"},   
    "ELEC_77"   : { "key" :"TOD Slot-5  (optional)", "values" :"2"},   
    "ELEC_78"   : { "key" :"TOD Slot-6  (optional)", "values" :"2"},   
    "ELEC_79"   : { "key" :"Reserved", "values" :"2"}, 
    "ELEC_80"   : { "key" :"Voltage Unbal  R Phase", "values" :"2"},
    "ELEC_81"   : { "key" :"Voltage Unbal Y Phase", "values" :"2"},    
    "ELEC_82"   : { "key" :"Voltage Unbal B Phase", "values" :"2"},    
    "ELEC_83"   : { "key" :"Current Unbal  R Phase", "values" :"2"},   
    "ELEC_84"   : { "key" :"Current Unbal Y Phase", "values" :"2"},    
    "ELEC_85"   : { "key" :"Current Unbal B Phase", "values" :"2"},    
    "ELEC_86"   : { "key" :"Additional Load (optional)", "values" :"2"},   
    "ELEC_87"   : { "key" :"Analog input 1", "values" :"2"},   
    "ELEC_88"   : { "key" :"Analog input 2", "values" :"2"},   
    "ELEC_89"   : { "key" :"Digital input 1", "values" :"2"},  
    "ELEC_90"   : { "key" :"Digital input 2", "values" :"2"},   
    "ELEC_91"   : { "key" :"Digital input 3", "values" :"2"},  
    "ELEC_92"   : { "key" :"Digital input 4", "values" :"2"},  
    "ELEC_93"   : { "key" :"VLL Max 2", "values" :"2"}, 
    "ELEC_94"   : { "key" :"VLL Min 2", "values" :"2"}, 
    "ELEC_95"   : { "key" :"VLN max 2", "values" :"2"}, 
    "ELEC_96"   : { "key" :"VLN min 2", "values" :"2"}, 
    "ELEC_97"   : { "key" :"Amps max 2", "values" :" 2"},
    "ELEC_98"   : { "key" :"Amps Min 2", "values" :"2"},  
    "ELEC_99"   : { "key" :"Frequency Max", "values" :"2"},   
    "ELEC_100"  : { "key" :"Frequency Min", "values" :"2"},   
    "ELEC_101"  : { "key" :"Watts Max", "values" :"2"},   
    "ELEC_102"  : { "key" :"Watts Min", "values" :"2"},   
    "ELEC_103"  : { "key" :"VAR max (absolute max)", "values" :"2"},  
    "ELEC_104"  : { "key" :"VAR min (absolute min)", "values" :"2"},  
    "ELEC_105"  : { "key" :"VA max", "values" :"2"},  
    "ELEC_106"  : { "key" :"VA min", "values" :"2"},  
    "ELEC_107"  : { "key" :"PF max (absolute max)", "values" :"2"},   
    "ELEC_108"  : { "key" :"PF min (absolute min)", "values" :"2"},   
    "ELEC_109"  : { "key" :"Analog input 1 max", "values" :"2"},  
    "ELEC_110"  : { "key" :"Analog input 1 Min", "values" :"2"},  
    "ELEC_111"  : { "key" :"Analog input 2 Max", "values" :"2"},  
    "ELEC_112"  : { "key" :"Analog input 2 min", "values" :"2"},  
    "ELEC_113"  : { "key" :"Maximum demand TOD slot 1 (optional)", "values" :"2"},    
    "ELEC_114"  : { "key" :"Maximum demand TOD slot 2 (optional)", "values" :"2"},    
    "ELEC_115"  : { "key" :"Maximum demand TOD slot 3 (optional)", "values" :"2"},
    "ELEC_116"  : { "key" :"Maximum demand TOD slot 4 (optional)", "values" :"2"},    
    "ELEC_117"  : { "key" :"Maximum demand TOD slot 1 occ Time (optional)", "values" :"2"},   
    "ELEC_118"  : { "key" :"Maximum demand TOD slot 1 occ Date (optional)", "values" :"2"},   
    "ELEC_119"  : { "key" :"Maximum demand TOD slot 2 occ Time (optional)", "values" :"2"},   
    "ELEC_120"  : { "key" :"Maximum demand TOD slot 2 occ Date (optional)", "values" :"2"},   
    "ELEC_121"  : { "key" :"Maximum demand TOD slot 3 occ Time (optional)", "values" :"2"},   
    "ELEC_122"  : { "key" :"Maximum demand TOD slot 3 occ Date (optional)", "values" :"2"},   
    "ELEC_123"  : { "key" :"Maximum demand TOD slot 4 occ Time (optional)", "values" :"2"},   
    "ELEC_124"  : { "key" :"Maximum demand TOD slot 4 occ Date (optional)", "values" :"2"}
};

exports.harmonicsField = {

    "HARM_1" : { "key" :"Voltage R Harmonics", "values" :"2"},
    "HARM_2" : { "key" :"Voltage Y Harmonics", "values" :"2"},
    "HARM_3" : { "key" :"Voltage B Harmonics", "values" :"2"},
    "HARM_4" : { "key" :"Current R Harmonics", "values" :"2"},
    "HARM_5" : { "key" :"Current Y Harmonics", "values" :"2"},
    "HARM_6" : { "key" :"Current B Harmonics", "values" :"2"},
    "HARM_7" : { "key" :"K factor Voltage R phase", "values" :"2"},
    "HARM_8" : { "key" :"K factor Voltage Y phase", "values" :"2"},
    "HARM_9" : { "key" :"K factor Voltage B phase", "values" :"2"},
    "HARM_10" : { "key" :"K factor Current R phase", "values" :"2"},
    "HARM_11" : { "key" :"K factor Current Y phase", "values" :"2"},
    "HARM_12" : { "key" :"K factor Current B phase", "values" :"2"},
    "HARM_13" : { "key" :"3rd harmonics Voltage R phase", "values" :"2"},
    "HARM_14" : { "key" :"3rd harmonics Voltage Y phase", "values" :"2"},
    "HARM_15" : { "key" :"3rd harmonics Voltage B phase", "values" :"2"},
    "HARM_16" : { "key" :"3rd harmonics Current R phase", "values" :"2"},
    "HARM_17" : { "key" :"3rd harmonics Current Y phase", "values" :"2"},
    "HARM_18" : { "key" :"3rd harmonics Current B phase", "values" :"2"},
    "HARM_19" : { "key" :"5th harmonics Voltage R phase", "values" :"2"},
    "HARM_20" : { "key" :"5th harmonics Voltage Y phase", "values" :"2"},
    "HARM_21" : { "key" :"5th harmonics Voltage B phase", "values" :"2"},
    "HARM_22" : { "key" :"5th harmonics Current R phase", "values" :"2"},
    "HARM_23" : { "key" :"5th harmonics Current Y phase", "values" :"2"},
    "HARM_24" : { "key" :"5th harmonics Current B phase", "values" :"2"},
    "HARM_25" : { "key" :"7th harmonics Voltage R phase", "values" :"2"},
    "HARM_26" : { "key" :"7th harmonics Voltage Y phase", "values" :"2"},
    "HARM_27" : { "key" :"7th harmonics Voltage B phase", "values" :"2"},
    "HARM_28" : { "key" :"7th harmonics Current R phase", "values" :"2"},
    "HARM_29" : { "key" :"7th harmonics Current Y phase", "values" :"2"},
    "HARM_30" : { "key" :"7th harmonics Current B phase", "values" :"2"},
    "HARM_31" : { "key" :"9th harmonics Voltage R phase", "values" :"2"},
    "HARM_32" : { "key" :"9th harmonics Voltage Y phase", "values" :"2"},
    "HARM_33" : { "key" :"9th harmonics Voltage B phase", "values" :"2"},
    "HARM_34" : { "key" :"9th harmonics Current R phase", "values" :"2"},
    "HARM_35" : { "key" :"9th harmonics Current Y phase", "values" :"2"},
    "HARM_36" : { "key" :"9th harmonics Current B phase", "values" :"2"},
    "HARM_37" : { "key" :"11th harmonics Voltage R phase", "values" :"2"},
    "HARM_38" : { "key" :"11th harmonics Voltage Y phase", "values" :"2"},
    "HARM_39" : { "key" :"11th harmonics Voltage B phase", "values" :"2"},
    "HARM_40" : { "key" :"11th harmonics Current R phase", "values" :"2"},
    "HARM_41" : { "key" :"11th harmonics Current Y phase", "values" :"2"},
    "HARM_42" : { "key" :"11th harmonics Current B phase", "values" :"2"},
    "HARM_43" : { "key" :"13th harmonics Voltage R phase", "values" :"2"},
    "HARM_44" : { "key" :"13th harmonics Voltage Y phase", "values" :"2"},
    "HARM_45" : { "key" :"13th harmonics Voltage B phase", "values" :"2"},
    "HARM_46" : { "key" :"13th harmonics Current R phase", "values" :"2"},
    "HARM_47" : { "key" :"13th harmonics Current Y phase", "values" :"2"},
    "HARM_48" : { "key" :"13th harmonics Current B phase", "values" :"2"},
    "HARM_49" : { "key" :"15th harmonics Voltage R phase", "values" :"2"},
    "HARM_50" : { "key" :"15th harmonics Voltage Y phase", "values" :"2"},
    "HARM_51" : { "key" :"15th harmonics Voltage B phase", "values" :"2"},
    "HARM_52" : { "key" :"15th harmonics Current R phase", "values" :"2"},
    "HARM_53" : { "key" :"15th harmonics Current Y phase", "values" :"2"},
    "HARM_54" : { "key" :"15th harmonics Current B phase", "values" :"2"},
    "HARM_55" : { "key" :"17th harmonics Voltage R phase", "values" :"2"},
    "HARM_56" : { "key" :"17th harmonics Voltage Y phase", "values" :"2"},
    "HARM_57" : { "key" :"17th harmonics Voltage B phase", "values" :"2"},
    "HARM_58" : { "key" :"17th harmonics Current R phase", "values" :"2"},
    "HARM_59" : { "key" :"17th harmonics Current Y phase", "values" :"2"},
    "HARM_60" : { "key" :"17th harmonics Current B phase", "values" :"2"},
    "HARM_61" : { "key" :"19th harmonics Voltage R phase", "values" :"2"},
    "HARM_62" : { "key" :"19th harmonics Voltage Y phase", "values" :"2"},
    "HARM_63" : { "key" :"19th harmonics Voltage B phase", "values" :"2"},
    "HARM_64" : { "key" :"19th harmonics Current R phase", "values" :"2"},
    "HARM_65" : { "key" :"19th harmonics Current Y phase", "values" :"2"},
    "HARM_66" : { "key" :"19th harmonics Current B phase", "values" :"2"},
    "HARM_67" : { "key" :"21st harmonics Voltage R phase", "values" :"2"},
    "HARM_68" : { "key" :"21st harmonics Voltage Y phase", "values" :"2"},
    "HARM_69" : { "key" :"21st harmonics Voltage B phase", "values" :"2"},
    "HARM_70" : { "key" :"21st harmonics Current R phase", "values" :"2"},
    "HARM_71" : { "key" :"21st harmonics Current Y phase", "values" :"2"},
    "HARM_72" : { "key" :"21st harmonics Current B phase", "values" :"2"},
    "HARM_73" : { "key" :"23rd harmonics Voltage R phase", "values" :"2"},
    "HARM_74" : { "key" :"23rd harmonics Voltage Y phase", "values" :"2"},
    "HARM_75" : { "key" :"23rd harmonics Voltage B phase", "values" :"2"},
    "HARM_76" : { "key" :"23rd harmonics Current R phase", "values" :"2"},
    "HARM_77" : { "key" :"23rd harmonics Current Y phase", "values" :"0"},
    "HARM_78" : { "key" :"23rd harmonics Current B phase", "values" :"2"},
    "HARM_79" : { "key" :"25th harmonics Voltage R phase", "values" :"2"},
    "HARM_80" : { "key" :"25th harmonics Voltage Y phase", "values" :"2"},
    "HARM_81" : { "key" :"25th harmonics Voltage B phase", "values" :"2"},
    "HARM_82" : { "key" :"25th harmonics Current R phase", "values" :"2"},
    "HARM_83" : { "key" :"25th harmonics Current Y phase", "values" :"2"},
    "HARM_84" : { "key" :"25th harmonics Current B phase", "values" :"2"},
    "HARM_85" : { "key" :"27th harmonics Voltage R phase", "values" :"2"},
    "HARM_86" : { "key" :"27th harmonics Voltage Y phase", "values" :"2"},
    "HARM_87" : { "key" :"27th harmonics Voltage B phase", "values" :"2"},
    "HARM_88" : { "key" :"27th harmonics Current R phase", "values" :"2"},
    "HARM_89" : { "key" :"27th harmonics Current Y phase", "values" :"2"},
    "HARM_90" : { "key" :"27th harmonics Current B phase", "values" :"2"},
    "HARM_91" : { "key" :"29th harmonics Voltage R phase", "values" :"2"},
    "HARM_92" : { "key" :"29th harmonics Voltage Y phase", "values" :"2"},
    "HARM_93" : { "key" :"29th harmonics Voltage B phase", "values" :" 0"},
    "HARM_94" : { "key" :"29th harmonics Current R phase", "values" :"0"},
    "HARM_95" : { "key" :"29th harmonics Current Y phase", "values" :"0"},
    "HARM_96" : { "key" :"29th harmonics Current B phase", "values" :"0"},
    "HARM_97" : { "key" :"31st harmonics Voltage R phase", "values" :"0"},
    "HARM_98" : { "key" :"31st harmonics Voltage Y phase", "values" :"0"},
    "HARM_99" : { "key" :"31st harmonics Voltage B phase", "values" :"0"},
    "HARM_100" : { "key" :"31st harmonics Current R phase", "values" :"0"},
    "HARM_101" : { "key" :"31st harmonics Current Y phase", "values" :"0"},
    "HARM_102" : { "key" :"31st harmonics Current B phase", "values" :"0"},
    "HARM_103" : { "key" :"2nd harmonics Voltage R phase", "values" :"0"},
    "HARM_104" : { "key" :"2nd harmonics Voltage Y phase", "values" :"0"},
    "HARM_105" : { "key" :"2nd harmonics Voltage B phase", "values" :"0"},
    "HARM_106" : { "key" :"2nd harmonics Current R phase", "values" :"0"},
    "HARM_107" : { "key" :"2nd harmonics Current Y phase", "values" :"0"},
    "HARM_108" : { "key" :"2nd harmonics Current B phase", "values" :"0"},
    "HARM_109" : { "key" :"4th harmonics Voltage R phase", "values" :"0"},
    "HARM_110" : { "key" :"4th harmonics Voltage Y phase", "values" :"0"},
    "HARM_111" : { "key" :"4th harmonics Voltage B phase", "values" :"0"},
    "HARM_112" : { "key" :"4th harmonics Current R phase", "values" :"0"},
    "HARM_113" : { "key" :"4th harmonics Current Y phase", "values" :"0"},
    "HARM_114" : { "key" :"4th harmonics Current B phase", "values" :"0"},
    "HARM_115" : { "key" :"6th harmonics Voltage R phase", "values" :"0"},
    "HARM_116" : { "key" :"6th harmonics Voltage Y phase", "values" :"0"},
    "HARM_117" : { "key" :"6th harmonics Voltage B phase", "values" :"0"},
    "HARM_118" : { "key" :"6th harmonics Current R phase", "values" :"0"},
    "HARM_119" : { "key" :"6th harmonics Current Y phase", "values" :"0"},
    "HARM_120" : { "key" :"6th harmonics Current B phase", "values" :"0"},
    "HARM_121" : { "key" :"8th harmonics Voltage R phase", "values" :"0"},
    "HARM_122" : { "key" :"8th harmonics Voltage Y phase", "values" :"0"},
    "HARM_123" : { "key" :"8th harmonics Voltage B phase", "values" :"0"},
    "HARM_124" : { "key" :"8th harmonics Current R phase", "values" :"0"},
    "HARM_125" : { "key" :"8th harmonics Current Y phase", "values" :"0"},
    "HARM_126" : { "key" :"8th harmonics Current B phase", "values" :"0"},
    "HARM_127" : { "key" :"10th harmonics Voltage R phase", "values" :"0"},
    "HARM_128" : { "key" :"10th harmonics Voltage Y phase", "values" :"0"},
    "HARM_129" : { "key" :"10th harmonics Voltage B phase", "values" :"0"},
    "HARM_130" : { "key" :"10th harmonics Current R phase", "values" :"0"},
    "HARM_131" : { "key" :"10th harmonics Current Y phase", "values" :"0"},
    "HARM_132" : { "key" :"10th harmonics Current B phase", "values" :"0"},
    "HARM_133" : { "key" :"12th harmonics Voltage R phase", "values" :"0"},
    "HARM_134" : { "key" :"12th harmonics Voltage Y phase", "values" :"0"},
    "HARM_135" : { "key" :"12th harmonics Voltage B phase", "values" :"0"},
    "HARM_136" : { "key" :"12th harmonics Current R phase", "values" :"0"},
    "HARM_137" : { "key" :"12th harmonics Current Y phase", "values" :"0"},
    "HARM_138" : { "key" :"12th harmonics Current B phase", "values" :"0"},
    "HARM_139" : { "key" :"14th harmonics Voltage R phase", "values" :"0"},
    "HARM_140" : { "key" :"14th harmonics Voltage Y phase", "values" :"0"},
    "HARM_141" : { "key" :"14th harmonics Voltage B phase", "values" :"0"},
    "HARM_142" : { "key" :"14th harmonics Current R phase", "values" :"0"},
    "HARM_143" : { "key" :"14th harmonics Current Y phase", "values" :"0"},
    "HARM_144" : { "key" :"14th harmonics Current B phase", "values" :"0"},
    "HARM_145" : { "key" :"16th harmonics Voltage R phase", "values" :"0"},
    "HARM_146" : { "key" :"16th harmonics Voltage Y phase", "values" :"0"},
    "HARM_147" : { "key" :"16th harmonics Voltage B phase", "values" :"0"},
    "HARM_148" : { "key" :"16th harmonics Current R phase", "values" :"0"},
    "HARM_149" : { "key" :"16th harmonics Current Y phase", "values" :"0"},
    "HARM_150" : { "key" :"16th harmonics Current B phase", "values" :"0"},
    "HARM_151" : { "key" :"18th harmonics Voltage R phase", "values" :"0"},
    "HARM_152" : { "key" :"18th harmonics Voltage Y phase", "values" :"0"},
    "HARM_153" : { "key" :"18th harmonics Voltage B phase", "values" :"0"},
    "HARM_154" : { "key" :"18th harmonics Current R phase", "values" :"0"},
    "HARM_155" : { "key" :"18th harmonics Current Y phase", "values" :"0"},
    "HARM_156" : { "key" :"18th harmonics Current B phase", "values" :"0"},
    "HARM_157" : { "key" :"20th harmonics Voltage R phase", "values" :"0"},
    "HARM_158" : { "key" :"20th harmonics Voltage Y phase", "values" :"0"},
    "HARM_159" : { "key" :"20th harmonics Voltage B phase", "values" :"0"},
    "HARM_160" : { "key" :"20th harmonics Current R phase", "values" :"0"},
    "HARM_161" : { "key" :"20th harmonics Current Y phase", "values" :"0"},
    "HARM_162" : { "key" :"20th harmonics Current B phase", "values" :"0"},
    "HARM_163" : { "key" :"22th harmonics Voltage R phase", "values" :"0"},
    "HARM_164" : { "key" :"22th harmonics Voltage Y phase", "values" :"0"},
    "HARM_165" : { "key" :"22th harmonics Voltage B phase", "values" :"0"},
    "HARM_166" : { "key" :"22th harmonics Current R phase", "values" :"0"},
    "HARM_167" : { "key" :"22th harmonics Current Y phase", "values" :"0"},
    "HARM_168" : { "key" :"22th harmonics Current B phase", "values" :"0"},
    "HARM_169" : { "key" :"24th harmonics Voltage R phase", "values" :"0"},
    "HARM_170" : { "key" :"24th harmonics Voltage Y phase", "values" :"0"},
    "HARM_171" : { "key" :"24th harmonics Voltage B phase", "values" :"0"},
    "HARM_172" : { "key" :"24th harmonics Current R phase", "values" :"0"},
    "HARM_173" : { "key" :"24th harmonics Current Y phase", "values" :"0"},
    "HARM_174" : { "key" :"24th harmonics Current B phase", "values" :"0"},
    "HARM_175" : { "key" :"26th harmonics Voltage R phase", "values" :"0"},
    "HARM_176" : { "key" :"26th harmonics Voltage Y phase", "values" :"0"},
    "HARM_177" : { "key" :"26th harmonics Voltage B phase", "values" :"0"},
    "HARM_178" : { "key" :"26th harmonics Current R phase", "values" :"0"},
    "HARM_179" : { "key" :"26th harmonics Current Y phase", "values" :"0"},
    "HARM_180" : { "key" :"26th harmonics Current B phase", "values" :"0"},
    "HARM_181" : { "key" :"28th harmonics Voltage R phase", "values" :"0"},
    "HARM_182" : { "key" :"28th harmonics Voltage Y phase", "values" :"0"},
    "HARM_183" : { "key" :"28th harmonics Voltage B phase", "values" :"0"},
    "HARM_184" : { "key" :"28th harmonics Current R phase", "values" :"0"},
    "HARM_185" : { "key" :"28th harmonics Current Y phase", "values" :"0"},
    "HARM_186" : { "key" :"28th harmonics Current B phase", "values" :"0"},
    "HARM_187" : { "key" :"30th harmonics Voltage R phase", "values" :"0"},
    "HARM_188" : { "key" :"30th harmonics Voltage Y phase", "values" :"0"},
    "HARM_189" : { "key" :"30th harmonics Voltage B phase", "values" :"0"},
    "HARM_190" : { "key" :"30th harmonics Current R phase", "values" :"0"},
    "HARM_191" : { "key" :"30th harmonics Current Y phase", "values" :"0"},
    "HARM_192" : { "key" :"30th harmonics Current B phase", "values" :"0"}
};