exports.PAYLOAD_SUCCESS        = "PAYLOAD_SUCCESSFULLY_STORED_IN_SERVER";
exports.PAYLOAD_INVALID        = "INVALID PAYLOAD VALUES";
exports.PAYLOAD_UNABLE_PROCESS = "UNABLE TO PROCESS PAYLOAD";
exports.SOCKET_TIMEOUT         = "SOCKET_TIMEOUT";